// web/src/components/x6/X6View.tsx
import "./X6View.less";
import React from "react";
import { Edge, Graph } from "@antv/x6";
import { DagreLayout } from "@antv/layout";
import { Dnd } from "@antv/x6-plugin-dnd";
import DraggableNode from "./DraggableNode";
import { nanoid } from "nanoid";
import { Space } from "tdesign-react";

const data = {
  nodes: [
    { id: "1", label: "node1", size: { width: 140, height: 40 } },
    { id: "2", label: "node2", size: { width: 140, height: 40 } },
    { id: "3", label: "node3", size: { width: 140, height: 40 } },
    { id: "4", label: "node4", size: { width: 140, height: 40 } },
  ],
  edges: [
    { id: nanoid(), source: "1", target: "2" },
    { id: nanoid(), source: "1", target: "3" },
    { id: nanoid(), source: "3", target: "4" },
  ],
};

export default class X6View extends React.Component {
  private container: HTMLDivElement;
  private dndContainer: HTMLDivElement;
  private graph: Graph;
  private dnd: Dnd;
  private data: any = data;
  private layout = new DagreLayout({
    type: "dagre",
    rankdir: "TB",
    align: "UL",
    ranksep: 30,
    nodesep: 15,
    controlPoints: true,
  });

  constructor(props: any) {
    super(props);
  }

  componentDidMount() {
    this.graph = new Graph({
      panning: true,
      container: this.container,
      background: {
        color: "#F2F7FA",
      },
    });

    this.dnd = new Dnd({
      target: this.graph,
    });

    const newModel = this.layout.layout(this.data);
    this.graph.fromJSON(newModel);
    this.graph.centerContent();
  }

  refContainer = (container: HTMLDivElement) => {
    this.container = container;
  };
  dndContainerRef = (container: HTMLDivElement) => {
    this.dndContainer = container;
  };

  onNodeDraging = (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
    console.log(event);
  };

  onMouseUp = (edge: Edge) => {
    const nodeId = nanoid();

    this.data.nodes.push({
      id: nodeId,
      shape: "rect",
      size: {
        width: 140,
        height: 40,
      },
      label: "newNode",
    });

    this.data.edges.push({ id: nanoid(), source: edge.source, target: nodeId });
    this.data.edges.push({ id: nanoid(), source: nodeId, target: edge.target });
    this.data.edges = this.data.edges.filter((e: Edge) => e.id !== edge.id);
    const newModel = this.layout.layout(this.data);
    this.graph.fromJSON(newModel);
  };

  render() {
    return (
      <div className="x6root">
        <div className="dnd-list" ref={this.dndContainerRef}>
          <Space direction="vertical">
            <DraggableNode graph={this.graph} onMouseUp={this.onMouseUp}>
              Job
            </DraggableNode>
            <DraggableNode graph={this.graph} onMouseUp={this.onMouseUp}>
              Wait
            </DraggableNode>
            <DraggableNode graph={this.graph} onMouseUp={this.onMouseUp}>
              Choice
            </DraggableNode>
          </Space>
        </div>
        <div className="x6container" ref={this.refContainer} />
      </div>
    );
  }
}

// web/src/components/x6/X6View.vue
<template>
    <div id="x6view">

    </div>
</template>

<script lang="ts" setup>
    import { DagreLayout, GridLayout } from '@antv/layout';
    import { Cell, CellView, Edge, Graph, Shape } from '@antv/x6';
    import { Graph as GraphLib } from "@antv/graphlib";
    import { onMounted, ref } from 'vue';


    const nodes = ref([
        {
            id: 'node1',
            x: 40,
            y: 40,
            width: 80,
            height: 40,
            label: 'node1',
            shape: 'ellipse',
        },
        {
            id: 'node2',
            x: 160,
            y: 180,
            width: 80,
            height: 40,
            label: 'node2',

        },
        {
            id: 'node3',
            x: 160,
            y: 180,
            width: 80,
            height: 40,
            label: 'node3',
        },
        {
            id: 'node4',
            x: 160,
            y: 180,
            width: 80,
            height: 40,
            label: 'node4',
            children: ['node5']
        },
        {
            id: 'node5',
            x: 160,
            y: 180,
            width: 80,
            height: 40,
            label: 'node5',
            parent: 'node4',
        },
    ])
    const edges = ref([
        {
            source: 'node1',
            target: 'node2',
        },
        {
            source: 'node1',
            target: 'node3',
        },
        {
            source: 'node3',
            target: 'node4',
        },
    ])

    const node5 = new Shape.Rect({
        id: 'node5',
        x: 140,
        y: 40,
        width: 100,
        height: 40,
        label: 'rect',
        zIndex: 2,
    })


    function initView() {
        const graph = new Graph({
            container: document.getElementById("x6view") || undefined,
            width: 800,
            height: 600,
            background: {
                color: '#fff',
            },
            grid: {
                type: "mesh",
                size: 10,      // 网格大小 10px
                visible: true, // 渲染网格背景
                args: {
                    color: '#ddd', // 网格线/点颜色
                    thickness: 1,     // 网格线宽度/网格点大小
                },
            },
            embedding: true,
            panning: {
                enabled: true,
            },
            connecting: {
                snap: true,
            },
            // interacting: (cellView: CellView) => {
            // },
        });
        // graph.fromJSON({ nodes: nodes.value, edges: edges.value })

        // graph.on('node:move', (args) => {
        //     console.log('move >', args)
        // })
        // graph.on('node:moving', (args) => {
        //     console.log('moving >', args)
        // })
        // graph.on('node:moved', (args) => {
        //     console.log('moved >', args)
        // })
        graph.on('dragenter', (e: any) => {
            console.log('moved >', e)
        });

        const gridLayout = new DagreLayout({
            type: "dagre",
            rankdir: 'TB',
            ranksep: 40,
            nodesep: 30,
            controlPoints: false,
        })

        const newModel = gridLayout.layout({ nodes: nodes.value, edges: edges.value })
        graph.fromJSON(newModel)
    }

    onMounted(() => {
        initView()
    })

</script>
