// web/src/views/FlowList.vue
<template>
  <m-view class="flow-list" hideBack title="任务流">
    <template #action>
      <t-button @click="onCreateFlow">创建工作流</t-button>
    </template>
    <t-table row-key="Id" :data="listData" :columns="columns" @row-click="onRowClick" hover>
    </t-table>
  </m-view>
</template>

<script setup lang="ts">
  import { ApiCreateFlow, ApiQueryFlow } from '@/api/flow';
  import type { Flow } from '@/util/types';
  import { onMounted, ref } from 'vue';
  import { useRouter } from 'vue-router';

  const columns = ref([
    { colKey: "Name", title: "名称" },
    { colKey: "Desc", title: "描述", width: 160 },
    { colKey: "CreateTime", title: "创建时间", width: 240, ellipsis: true },
  ]);
  const listData = ref<Array<Flow>>([])

  const router = useRouter()
  const onRowClick = ({ row }: { row: Flow }) => {
    router.push({ name: "flow_detail", params: { id: row.Id } });
  };
  const requestList = () => {
    ApiQueryFlow().then((res) => {
      listData.value = res.data.list;
    });
  };

  const onCreateFlow = () => {
    ApiCreateFlow({}).then((res) => {
      if (res.code == 0) {
        router.push({ name: "flow_version_edit", params: { id: res.data.Id } });
      }
    });
  };

  onMounted(() => {
    requestList();
  });
</script>

<style lang="less" scoped>
  .flow-list {
    width: 100%;
    height: 100%;
    padding: 10px;
  }
</style>

// web/src/pages/flow/FlowList.tsx
import { Button, PrimaryTable } from "tdesign-react"
import PageView from "../../components/PageView"
import { useEffect, useState } from "react"
import { ApiQueryFlow } from "../../apis/flow"
import { Flow } from "../../utils/types"
import { useNavigate } from "react-router-dom"

export default () => {
    const [tableData, setTableData] = useState<Flow[]>([])
    const columns = [
        { colKey: "Name", title: "名称" },
        { colKey: "Desc", title: "描述", width: 160 },
        { colKey: "CreateTime", title: "创建时间", width: 240, ellipsis: true },
    ]
    function requestList() {
        ApiQueryFlow().then(resp => {
            if (resp.code == 0) {
                console.log(resp.data)
                setTableData(resp.data.list)
            }
        })
    }

    useEffect(() => {
        requestList()
    }, [])

    const navigate = useNavigate()
    function handleRowClick({ row }: { row: Flow }) {
        navigate("/flow/" + row.Id)
    }

    return (
        <PageView title="FlowList" hideBack action={<Button>新建工作流</Button>}>
            <PrimaryTable
                rowKey="Id"
                columns={columns}
                data={tableData}
                pagination={{ defaultPageSize: 10, total: 30 }}
                size="medium"
                tableLayout="fixed"
                verticalAlign="middle"
                hover
                onRowClick={handleRowClick}
            />
        </PageView >
    )
}
